# Generated by Django 3.0.7 on 2021-02-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativeinfo',
            name='scraped',
            field=models.BooleanField(default=False),
        ),
    ]
