# Generated by Django 3.0.7 on 2021-03-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adfile',
            name='ad_filepath',
            field=models.TextField(default='', unique=True),
            preserve_default=False,
        ),
    ]
